### ISSUE TITLE
Debian stretch (stable) compile error

### ISSUE THREAD

**Issue by druppy** [dveselov/go-libreofficekit#6]
Hi ...
I tried to install this nice go pkg on my debian stable, that uses `libreofficekit-dev 5.2.7`, but this error happend.

```In file included from go/src/github.com/dveselov/go-libreofficekit/libreofficekit.go:6:0:
./lokbridge.h: In function 'get_views_count':
./lokbridge.h:70:25: error: 'LibreOfficeKitDocumentClass {aka struct _LibreOfficeKitDocumentClass}' has no member named 'getViewsCount'; did you mean 'getViews'?
     return pThis->pClass->getViewsCount(pThis);
                         ^~
```
What versions are needed of this lib in order to make this compile ?

**Comment by acaloiaro** [comment]
See https://github.com/dveselov/go-libreofficekit/issues/5#issuecomment-374425803

**Comment by druppy** [comment]
Perfect, I updated my debian stable to a backport libreoffice (5.2.7 -> 6.0.0), and now it compiles without complains.

The main README.md state ```# Latest version of LibreOffice (5.2) is required``` and this may be a good idea to update in the text, to eliminate future confusion ?

Thanks for your nice work, I will try to use this for some PDF generation.
