### ISSUE TITLE
About newOffice path

### ISSUE THREAD

**Issue by elvisNg** [dveselov/go-libreofficekit#8]
the path should be the docx path  or others? 
pull the docxPath will export the nil pointers:

root@800-180329-PC:/usr/local/GoWorkspace# go run packageMain.go
installation path "usr/local/GoWorkspace/" does not exist
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x488ec3]

goroutine 1 [running]:
_/usr/local/GoWorkspace/libreofficekit.(*Office).LoadDocument(0x0, 0x4bc8db, 0x9, 0x0, 0x0, 0x0)
        /usr/local/GoWorkspace/libreofficekit/libreofficekit.go:78 +0x93
main.main()
        /usr/local/GoWorkspace/packageMain.go:7 +0x62
exit status 2
root@800-180329-PC:/usr/local/GoWorkspace#

the docx path is :/usr/local/GoWorkspace/test.docx
root@800-180329-PC:/usr/local/GoWorkspace# ls
libreofficekit  packageMain.go  packageMain.sublime-workspace  test.docx

thankyou!!!

**Comment by dveselov** [comment]
Hi,
Path that passed to newOffice function is a location of system libreoffice, on debian-like systems it's usually `/usr/lib/libreoffice/program/`
Take a look at tests for inspiration: https://github.com/dveselov/go-libreofficekit/blob/master/libreofficekit_test.go#L9
