### ISSUE TITLE
How to convert the pdf support chinese ?

### ISSUE THREAD

**Issue by elvisNg** [dveselov/go-libreofficekit#9]
hi dve.
How to convert the pdf support chinese ?

func main() {
    office, _ := libreofficekit.NewOffice("/usr/lib/libreoffice/program/")
    
    document, _ := office.LoadDocument("test.docx")
    document.SaveAs("test.pdf", "pdf", "skipImages")

    document.Close()
    office.Close()
}

Thanks a lot and look forward to hearing from you soon.
Best Regards,
jjw

**Comment by acaloiaro** [comment]
You'll want to add some additional font packages to your system. For example, if you use Ubuntu, these are the packages that I install to support a wide range of languages:

```
        fonts-arphic-ukai \
        fonts-arphic-uming \
        fonts-dejavu \
        fonts-dejavu-core \
        fonts-dejavu-extra \
        fonts-ipafont-gothic \
        fonts-ipafont-mincho \
        fonts-liberation \
        fonts-nanum \
        fonts-nanum-extra \
        fonts-noto-cjk \
        fonts-noto-mono \
        fonts-opensymbol \
        fonts-sil-gentium \
        fonts-sil-gentium-basic \
        fonts-stix \
        fonts-unfonts-core \
```
